service: infi-scheduler-lambda

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  profile: ${file(./env_${opt:stage, 'dev'}.yaml):profile}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:StartInstances
        - ec2:StopInstances
        - ec2:DescribeInstances
      Resource: "*"
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: "*"

custom:
  TAGS: schedule-lambda
  stage: ${opt:stage, 'dev'}

functions:
  start-instances:
    handler: handler.start_instances

  end-instances:
    handler: handler.end_instances
